Accounts/urls.py
from django.urls import path
from . import views

#below are the URL to call the function in view file
#in the account app URL goes like
#        .../account/login/ or acccounts/signup/ or just account/
app_name = 'Accounts'

urlpatterns = [
    path("",views.profile_view,name="profile_view"),
    path("login/",views.login_view,name="login_view"),
    path("signup/",views.signup_view,name="signup_view"),
    path("signout/",views.signout,name="signout"),
    path('profile-info/',views.profile_info,name="personal_info"),
    path('activate/<uidb64>/<token>',views.activate_acc,name="activate"),
    path('changename/',views.check_auth,name="change_name"),
    path('change/',views.change_name,name="change"),
    path('changepass/',views.change_pass,name="change_pass")
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Ayojan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('MainPage.urls')),
    path('account/',include('Accounts.urls')),    
    path('accounts/',include("allauth.urls")),
    path('booking/',include('Booking.urls')),
    path('payment/',include('Payment.urls'))

]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Booking/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "Booking"


urlpatterns = [
    path("",views.bookingpage,name ='bookingpage'),
    path("search/",views.search_page,name ='search_view'),
    path("form/<int:venue_id>",views.bookingform,name="booking_form"),
    path("Venue/<int:venue_id>",views.venuepage,name="venuepage"),
    path("list/",views.cartpage,name="cartpage"),
    path("succefullyadded/<int:venue_id>",views.bookinglistadder,name="bookinglistadder"),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('search-suggestions-professionals/', views.search_suggestions_prof, name='search_suggestions_prof'),
    path('checkout/',views.checkout_verification,name="checkout"),
    path('professionals/',views.booking_professional_page,name="professional"),
    path('professional/<int:professional_id>',views.professional_page,name='professionalspage'),
    path('professionalsform/<int:professional_id>',views.professionalsbookingform,name="professionalsbookingform"),
    path('succesfullyaddedprofessional/<int:professional_id>',views.professionalsbookinglistadder,name="professionalsbookinglistadder"),
    path('arview/<int:venue_id>',views.arview,name="arview")



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MainPage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

#below are the URL to call the function in view file
#in the mainpage app URL goes like
#        .../    just a slash.

app_name = 'MainPage'

urlpatterns = [
    path("",views.landing_view,name="mainpage"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Booking/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import JsonResponse
from .search_logic import search_venues, search_professionals
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

#below i have created the search login for search page and booking page
def bookingpage(request):
    search_results = search_venues(request)
    if search_results is not None:
        return render(request, 'Booking/bookingpage.html', {'venues': search_results})
    else:
        venues = Venues.objects.all()
    # Implement pagination
    paginator = Paginator(venues, 21)  # Show 20 venues per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'venues': page_obj,
    }
    return render(request, 'Booking/bookingpage.html', context)    
    

def search_page(request):
    search_results = search_venues(request)
    if search_results is not None:
        return render(request, 'Booking/bookingpage.html', {'venues': search_results})
        
    else:
        return render(request , 'Booking/searchpage.html')
    



#below i have created the booking form funciton this grabs the data from the form and created a booking in database.

def bookingform(request,venue_id=0):
    if request.method == "POST":
        #additionally this handels the updation of incomplete forms
        booking_ids = request.POST.getlist('booking_id')
        incomplete_bookings = Booking.objects.filter(id__in=booking_ids)
        if booking_ids :
            for booking in incomplete_bookings:
                if booking.venue :
                    # Extract details from the form
                    start_date = request.POST[f"start_date_{booking.id}"]
                    end_date = request.POST[f"end_date_{booking.id}"]
                    num_people = int(request.POST[f"num_people_{booking.id}"])
                    event_type = request.POST[f"event_type_{booking.id}"]
                    food_type = request.POST[f"food_type_{booking.id}"]
                    decoration_needed = request.POST[f"decoration_needed_{booking.id}"].lower() == "yes"
                    time_duration = request.POST[f"time_duration_{booking.id}"]
                    additional_services = request.POST[f"additional_services_{booking.id}"]

                    # Update the attributes of the booking object
                    booking.start_date = start_date
                    booking.end_date = end_date
                    booking.num_people = num_people
                    booking.event_type = event_type
                    booking.food_type = food_type
                    booking.decoration_needed = decoration_needed
                    booking.time_duration = time_duration
                    booking.additional_services = additional_services

                    # Grabbing the user & the venue
                    user = request.user
                    venue = get_object_or_404(Venues, pk=venue_id)

                    start_date_cpy = datetime.strptime(start_date, "%Y-%m-%d")
                    end_date_cpy = datetime.strptime(end_date, "%Y-%m-%d")

                    # Calculate the duration in days
                    duration_days = (end_date_cpy - start_date_cpy).days

                    # Calculate the total price
                    total_price = venue.calculate_price(num_guests=num_people, event_type=event_type, duration=duration_days)
                    
                    # Update the total price of the booking
                    booking.total_price = total_price

                    # Save the updated booking object
                    booking.save()
                    
                
                elif booking.professional :
                    # Extract details from the form
                    start_date = request.POST[f"start_date_{booking.id}"]
                    end_date = request.POST[f"end_date_{booking.id}"]
                    event_type = request.POST[f"event_type_{booking.id}"]
                    

                    # Update the attributes of the booking object
                    booking.start_date = start_date
                    booking.end_date = end_date
                    booking.num_people = 1
                    booking.event_type = event_type
                    booking.food_type = "NOTHING"
                    booking.decoration_needed = False
                    
                    booking.additional_services = "NOTHING"

                    # Grabbing the user
                    user = request.user
                    

                    start_date_cpy = datetime.strptime(start_date, "%Y-%m-%d")
                    end_date_cpy = datetime.strptime(end_date, "%Y-%m-%d")

                    # Calculate the duration in days
                    duration_days = (end_date_cpy - start_date_cpy).days
                    booking.time_duration = duration_days
                    # Calculate the total price
                    total_price = duration_days*24*(booking.professional.price_range)
                    
                    # Update the total price of the booking
                    booking.total_price = total_price

                    # Save the updated booking object
                    booking.save()
            booking = Booking.objects.filter(user = user)
            return render(request, 'Booking/cartpage.html', {'bookings':booking})
        else:
        
            # Extracting the details of the booking from the Form
            start_date = request.POST["start_date"]
            end_date = request.POST["end_date"]

            #converting the num_people form str to int
            num_people = request.POST["num_people"]
            num_people = int(num_people)
            
            event_type = request.POST["event_type"]
            food_type = request.POST["food_type"]
            decoration_needed = request.POST["decoration_needed"]
            time_duration = request.POST["time_duration"]
            additional_services = request.POST["additional_services"]

            #As decoration need is a boolean feild
            if decoration_needed.lower() == "yes":
                decoration_needed = True
            else:
                decoration_needed = False
            
            # Grabbing the user & the venue
            user = request.user
            venue = get_object_or_404(Venues, pk=venue_id)

            start_date_cpy = datetime.strptime(start_date, "%Y-%m-%d")
            end_date_cpy = datetime.strptime(end_date, "%Y-%m-%d")

            # Calculate the duration in days
            duration_days = (end_date_cpy - start_date_cpy).days

            # Calling the funtion in the Venues model for calculation the price.
            total_price = venue.calculate_price(num_guests= num_people,event_type= event_type,duration=duration_days)


            # Create and save a new Booking object
            booking = Booking.objects.create(
                start_date=start_date,
                end_date=end_date,
                num_people=num_people,
                event_type=event_type,
                food_type=food_type,
                decoration_needed=decoration_needed,
                time_duration=time_duration,
                additional_services=additional_services,
                user=user, 
                venue=venue,
                total_price = total_price,
                payment_status = "UNDECIDED",
            )
            return redirect('MainPage:mainpage') #this will actually be redirected to payment page.
        
        
    else:   
    
        context = get_object_or_404(Venues,pk=venue_id) 
        return render(request, 'Booking/bookingform.html',{'venue':context})
        

#Below function loads up the page for a specific venue that is being clicked on
def venuepage(request,venue_id):
    venue = get_object_or_404(Venues,pk=venue_id)
    bookings = Booking.objects.filter(venue_id = venue_id)
    reviews = Review.objects.filter(venue_id=venue_id)
    if bookings == None :
        bookings = []
        return render(request,'Booking/venuepage.html',{'venue':venue,'bookings':bookings,'reviews':reviews})
    else:    
        return render(request,'Booking/venuepage.html',{'venue':venue,'bookings':bookings,'reviews':reviews})



#The below function adds the Venue to be Booked without any details with just user and what venue
#other details can be taken care of at the Cartpage

def bookinglistadder(request,venue_id):
    user = request.user
    venue = get_object_or_404(Venues, pk=venue_id)
    if not user.is_authenticated:   # the simple lazy object error resolved, happend when no user is logged in as program tries to assign it a booking
        return redirect('Accounts/login_page.html')

    booking = Booking.objects.create(
            user=user, 
            venue=venue,
            payment_status = "UNDECIDED",
    )
    venues = Venues.objects.all()
    paginator = Paginator(venues, 21)  # Show 20 venues per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'venues': page_obj,
    }
    return render(request, 'Booking/bookingpage.html', context)





#Below function loads up the cart page
def cartpage(request):
    #creating seprate html page for authenticated and not authenticated user
    if request.user.is_authenticated:
        user = request.user
        booking = Booking.objects.filter(user = user, booking_status = False)
        return render(request, 'Booking/cartpage.html', {'bookings':booking})
    else :
        booking = []
        return render(request, 'Booking/cartpage.html', {'bookings':booking})
    


#below function is for search suggestion when a person types in search bar
def search_suggestions(request):

Booking/templates/Booking/bookingpage.html
{% extends 'Booking/common.html' %}
{% load static %}
{% block content %}
<div class="navbar">

    <div class="left-navbar">
         <a href="{% url 'MainPage:mainpage'%}"><img id="navbar-logo" src=".{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo"></a>
         <div class="nav-btn">
             <a href="{% url 'Booking:bookingpage'%}">Venues</a>
         </div>
         <div class="nav-btn">
             <a href="{% url 'Booking:professional'%}">Professionals</a>
         </div>
    </div>

         
     <div class="right-navbar">
         <div class="profile-or-login">
             {% if user.is_authenticated %}
                 <a href="{% url 'Accounts:profile_view' %}"><svg class="profile-btn-icon" xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="#000000"><path d="M226-262q59-42.33 121.33-65.5 62.34-23.17 132.67-23.17 70.33 0 133 23.17T734.67-262q41-49.67 59.83-103.67T813.33-480q0-141-96.16-237.17Q621-813.33 480-813.33t-237.17 96.16Q146.67-621 146.67-480q0 60.33 19.16 114.33Q185-311.67 226-262Zm253.88-184.67q-58.21 0-98.05-39.95Q342-526.58 342-584.79t39.96-98.04q39.95-39.84 98.16-39.84 58.21 0 98.05 39.96Q618-642.75 618-584.54t-39.96 98.04q-39.95 39.83-98.16 39.83ZM480.31-80q-82.64 0-155.64-31.5-73-31.5-127.34-85.83Q143-251.67 111.5-324.51T80-480.18q0-82.82 31.5-155.49 31.5-72.66 85.83-127Q251.67-817 324.51-848.5T480.18-880q82.82 0 155.49 31.5 72.66 31.5 127 85.83Q817-708.33 848.5-635.65 880-562.96 880-480.31q0 82.64-31.5 155.64-31.5 73-85.83 127.34Q708.33-143 635.65-111.5 562.96-80 480.31-80Zm-.31-66.67q54.33 0 105-15.83t97.67-52.17q-47-33.66-98-51.5Q533.67-284 480-284t-104.67 17.83q-51 17.84-98 51.5 47 36.34 97.67 52.17 50.67 15.83 105 15.83Zm0-366.66q31.33 0 51.33-20t20-51.34q0-31.33-20-51.33T480-656q-31.33 0-51.33 20t-20 51.33q0 31.34 20 51.34 20 20 51.33 20Zm0-71.34Zm0 369.34Z"/></svg></a>
             {% else %}
                 <a href="{% url 'Accounts:login_view' %}"><svg class="login-btn-icon" xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 -960 960 960" width="30px" fill="#000000"><path d="M480.67-120v-66.67h292.66v-586.66H480.67V-840h292.66q27 0 46.84 19.83Q840-800.33 840-773.33v586.66q0 27-19.83 46.84Q800.33-120 773.33-120H480.67Zm-63.34-176.67-47-48 102-102H120v-66.66h351l-102-102 47-48 184 184-182.67 182.66Z"/></svg></a>
             {% endif %}
         </div>
         <div class="cart-button">
             <a href="{% url 'Booking:cartpage' %}"><svg class="cart-btn-icon" xmlns="http://www.w3.org/2000/svg" height="34px" viewBox="0 -960 960 960" width="34px" fill="#000000"><path d="M284.53-80.67q-30.86 0-52.7-21.97Q210-124.62 210-155.47q0-30.86 21.98-52.7Q253.95-230 284.81-230t52.69 21.98q21.83 21.97 21.83 52.83t-21.97 52.69q-21.98 21.83-52.83 21.83Zm400 0q-30.86 0-52.7-21.97Q610-124.62 610-155.47q0-30.86 21.98-52.7Q653.95-230 684.81-230t52.69 21.98q21.83 21.97 21.83 52.83t-21.97 52.69q-21.98 21.83-52.83 21.83ZM238.67-734 344-515.33h285.33l120-218.67H238.67ZM206-800.67h589.38q22.98 0 34.97 20.84 11.98 20.83.32 41.83L693.33-490.67q-11 19.34-28.87 30.67-17.87 11.33-39.13 11.33H324l-52 96h487.33V-286H278q-43 0-63-31.83-20-31.84-.33-68.17l60.66-111.33-149.33-316H47.33V-880h121.34L206-800.67Zm138 285.34h285.33H344Z"/></svg></a>
         </div>
    </div>
 </div>
<link rel="stylesheet" href="..{% static 'Booking/CSS/booking.css'%}">
<header>
    
    <div class="search-container">
      
        <div class="search-by-type">
            <form id="search-form" method="GET">
                <div class="search-bar">
                    <input type="text" id="search-bar" name="search" placeholder="Search for venues..." autocomplete="off">
                    <button type="submit">    
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M792-120.67 532.67-380q-30 25.33-69.64 39.67Q423.39-326 378.67-326q-108.44 0-183.56-75.17Q120-476.33 120-583.33t75.17-182.17q75.16-75.17 182.5-75.17 107.33 0 182.16 75.17 74.84 75.17 74.84 182.27 0 43.23-14 82.9-14 39.66-40.67 73l260 258.66-48 48Zm-414-272q79.17 0 134.58-55.83Q568-504.33 568-583.33q0-79-55.42-134.84Q457.17-774 378-774q-79.72 0-135.53 55.83-55.8 55.84-55.8 134.84t55.8 134.83q55.81 55.83 135.53 55.83Z"/></svg>
                    </button>
                </div>
            </form>
            <button id="openFilterMenuBtn">
                <svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="#000000"><path d="M286.67-613.33V-680H840v66.67H286.67Zm0 166.66v-66.66H840v66.66H286.67Zm0 166.67v-66.67H840V-280H286.67ZM153.33-613.33q-13.66 0-23.5-9.84Q120-633 120-647q0-14 9.83-23.5 9.84-9.5 23.84-9.5t23.5 9.58q9.5 9.59 9.5 23.75 0 13.67-9.59 23.5-9.58 9.84-23.75 9.84Zm0 166.66q-13.66 0-23.5-9.83-9.83-9.83-9.83-23.83 0-14 9.83-23.5 9.84-9.5 23.84-9.5t23.5 9.58q9.5 9.58 9.5 23.75 0 13.67-9.59 23.5-9.58 9.83-23.75 9.83Zm0 166.67q-13.66 0-23.5-9.83-9.83-9.84-9.83-23.84t9.83-23.5q9.84-9.5 23.84-9.5t23.5 9.59q9.5 9.58 9.5 23.75 0 13.66-9.59 23.5-9.58 9.83-23.75 9.83Z"/></svg></button>
            <div id="filterMenu" class="search-by-filter"> 
                <a href="javascript:void(0)" class="closebtn" id="closeFilterMenuBtn">&times;</a>
                <form id="filter-form" name="filter" method="GET">
                    <div class="filters">
                        <h3>Filters</h3>
                        <div class="filter">
                            <label for="baseprice">Base Price:</label>
                            <input type="number" id="baseprice" name="baseprice" placeholder="Enter maximum price">
                        </div>
                        <div class="filter">
                            <label for="city">City:</label>
                            <input type="text" id="city" name="city" placeholder="Enter city">
                        </div>
                        <div class="filter">
                            <label for="state">State:</label>
                            <input type="text" id="state" name="state" placeholder="Enter state">
                        </div>
                    </div>
                    <button type="submit">Apply Filters</button>
                </form>
            </div>
            
    </div>
</header>
<main class="venue-section">
    <section class="venue-list">
        {% for venue in venues %}
        <!-- <a id = "wrapper-link" href="{% url 'Booking:venuepage' venue.id %}"> -->
            <div class="venue-item">
                <div class="venue-info">
                    <div class="venue-img">
                        <img  id="img" src=".{{ venue.image.url }}" alt="venue">
                    </div>
                    <h2>{{ venue.venue_name }}</h2>
                    <p>Location: {{ venue.city }}, {{ venue.state }}</p>
                    <p>Price: {{ venue.base_price }}</p>
                    
                    {% if user.is_authenticated %}
                        <a href="{% url 'Booking:booking_form' venue.id %}"><button>Book Now</button></a>
                    {% else %}
                        <a href="{% url 'Accounts:login_view' %}"><button>login to Book</button></a>
                    {% endif %}

                    <a href="{% url 'Booking:venuepage' venue.id %}"><button>View</button></a>
                    <a href="{% url 'Booking:bookinglistadder' venue.id %}"><button>Add to Booking List</button></a>
                </div>
            </div>
        <!-- </a> -->
        {% endfor %}
    </section>

    <div class="pagination">
        <span class="step-links">
            {% if venues.has_previous %}
                <a href="?page=1">&laquo;</a>
                <a href="?page={{ venues.previous_page_number }}"> < </a>
            {% endif %}

            <span class="current">
                {{ venues.number }}/{{ venues.paginator.num_pages }}
            </span>

            {% if venues.has_next %}
                <a href="?page={{ venues.next_page_number }}"> > </a>
                <a href="?page={{ venues.paginator.num_pages }}">&raquo;</a>
            {% endif %}
        </span>
    </div>
</main>

{% endblock content %}

Booking/templates/Booking/cartpage.html
{% extends 'Booking/common.html' %}
{% load static %}
{% block content %}
<div class="navbar">

    <div class="left-navbar">
         <a href="{% url 'MainPage:mainpage'%}"><img id="navbar-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo"></a>
         <div class="nav-btn">
             <a href="{% url 'Booking:bookingpage'%}">Venues</a>
         </div>
         <div class="nav-btn">
             <a href="{% url 'Booking:professional'%}">Professionals</a>
         </div>
    </div>

         
     <div class="right-navbar">
         <div class="profile-or-login">
             {% if user.is_authenticated %}
                 <a href="{% url 'Accounts:profile_view' %}"><svg class="profile-btn-icon" xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="#000000"><path d="M226-262q59-42.33 121.33-65.5 62.34-23.17 132.67-23.17 70.33 0 133 23.17T734.67-262q41-49.67 59.83-103.67T813.33-480q0-141-96.16-237.17Q621-813.33 480-813.33t-237.17 96.16Q146.67-621 146.67-480q0 60.33 19.16 114.33Q185-311.67 226-262Zm253.88-184.67q-58.21 0-98.05-39.95Q342-526.58 342-584.79t39.96-98.04q39.95-39.84 98.16-39.84 58.21 0 98.05 39.96Q618-642.75 618-584.54t-39.96 98.04q-39.95 39.83-98.16 39.83ZM480.31-80q-82.64 0-155.64-31.5-73-31.5-127.34-85.83Q143-251.67 111.5-324.51T80-480.18q0-82.82 31.5-155.49 31.5-72.66 85.83-127Q251.67-817 324.51-848.5T480.18-880q82.82 0 155.49 31.5 72.66 31.5 127 85.83Q817-708.33 848.5-635.65 880-562.96 880-480.31q0 82.64-31.5 155.64-31.5 73-85.83 127.34Q708.33-143 635.65-111.5 562.96-80 480.31-80Zm-.31-66.67q54.33 0 105-15.83t97.67-52.17q-47-33.66-98-51.5Q533.67-284 480-284t-104.67 17.83q-51 17.84-98 51.5 47 36.34 97.67 52.17 50.67 15.83 105 15.83Zm0-366.66q31.33 0 51.33-20t20-51.34q0-31.33-20-51.33T480-656q-31.33 0-51.33 20t-20 51.33q0 31.34 20 51.34 20 20 51.33 20Zm0-71.34Zm0 369.34Z"/></svg></a>
             {% else %}
                 <a href="{% url 'Accounts:login_view' %}"><svg class="login-btn-icon" xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 -960 960 960" width="30px" fill="#000000"><path d="M480.67-120v-66.67h292.66v-586.66H480.67V-840h292.66q27 0 46.84 19.83Q840-800.33 840-773.33v586.66q0 27-19.83 46.84Q800.33-120 773.33-120H480.67Zm-63.34-176.67-47-48 102-102H120v-66.66h351l-102-102 47-48 184 184-182.67 182.66Z"/></svg></a>
             {% endif %}
         </div>
         <div class="cart-button">
             <a href="{% url 'Booking:cartpage' %}"><svg class="cart-btn-icon" xmlns="http://www.w3.org/2000/svg" height="34px" viewBox="0 -960 960 960" width="34px" fill="#000000"><path d="M284.53-80.67q-30.86 0-52.7-21.97Q210-124.62 210-155.47q0-30.86 21.98-52.7Q253.95-230 284.81-230t52.69 21.98q21.83 21.97 21.83 52.83t-21.97 52.69q-21.98 21.83-52.83 21.83Zm400 0q-30.86 0-52.7-21.97Q610-124.62 610-155.47q0-30.86 21.98-52.7Q653.95-230 684.81-230t52.69 21.98q21.83 21.97 21.83 52.83t-21.97 52.69q-21.98 21.83-52.83 21.83ZM238.67-734 344-515.33h285.33l120-218.67H238.67ZM206-800.67h589.38q22.98 0 34.97 20.84 11.98 20.83.32 41.83L693.33-490.67q-11 19.34-28.87 30.67-17.87 11.33-39.13 11.33H324l-52 96h487.33V-286H278q-43 0-63-31.83-20-31.84-.33-68.17l60.66-111.33-149.33-316H47.33V-880h121.34L206-800.67Zm138 285.34h285.33H344Z"/></svg></a>
         </div>
    </div>
 </div>

<link rel="stylesheet" href="..{% static 'Booking/CSS/booking.css'%}">
    {% if user.is_authenticated %}
        {% if bookings %}
        <div class="cart">
            <h2>Booking List</h2>
        
                <!-- Venue Item -->
                {% for booking in bookings %}
                {% if booking.venue.id %}
                <div class="cart-info">
                    <div class="venue-img">
                        <img  id="img" src="..{{ booking.venue.image.url }}" alt="venue">
                    </div>
                    <div class="info" >
                        <h2>{{ booking.venue.venue_name }}</h2>
                        <p>Location: {{ booking.venue.city }}, {{ booking.venue.state }}, {{ booking.venue.address }}</p>
                        <p>Price: {{ booking.total_price }}</p>
                    </div>

                </div>
                {% endif %}
                
                {% if booking.professional.id %}
                <div class="cart-info">
                    <div class="venue-img">
                        <img  id="img" src="..{{ booking.professional.image.url }}" alt="venue">
                    </div>
                    <div class="info">
                        <h2>{{ booking.professional.name }}</h2>
                        <p>{{ booking.professional.profession }}</p>
                        <p>Price: {{ booking.professional.price_range }}</p>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
           
    
        
            <div class="total-price">
                <p>Total Price: $2300</p>
            </div>
        
            <form method="POST" action="{% url 'Booking:checkout' %}">
                {% csrf_token %}
                {% for booking in bookings %}
                    <input type="hidden" name="booking_ids" value="{{ booking.id }}">
                {% endfor %}
                <button id="checkout-button" type="submit">Proceed to Checkout</button>
            </form>
        </div>
        {% else %}
        <div>Add something in your cart!</div>
        {% endif %}
    {% else %}
        <div><h1>Login to see What's in your Booking List</h1></div>
    {% endif %}
{% endblock content %}