Accounts/urls.py
from django.urls import path
from . import views

#below are the URL to call the function in view file
#in the account app URL goes like
#        .../account/login/ or acccounts/signup/ or just account/
app_name = 'Accounts'

urlpatterns = [
    path("",views.profile_view,name="profile_view"),
    path("login/",views.login_view,name="login_view"),
    path("signup/",views.signup_view,name="signup_view"),
    path("signout/",views.signout,name="signout"),
    path('profile-info/',views.profile_info,name="personal_info"),
    path('activate/<uidb64>/<token>',views.activate_acc,name="activate"),
    path('changename/',views.check_auth,name="change_name"),
    path('change/',views.change_name,name="change"),
    path('changepass/',views.change_pass,name="change_pass")
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Ayojan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('MainPage.urls')),
    path('account/',include('Accounts.urls')),    
    path('accounts/',include("allauth.urls")),
    path('booking/',include('Booking.urls')),
    path('payment/',include('Payment.urls'))

]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Booking/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "Booking"


urlpatterns = [
    path("",views.bookingpage,name ='bookingpage'),
    path("search/",views.search_page,name ='search_view'),
    path("form/<int:venue_id>",views.bookingform,name="booking_form"),
    path("Venue/<int:venue_id>",views.venuepage,name="venuepage"),
    path("list/",views.cartpage,name="cartpage"),
    path("succefullyadded/<int:venue_id>",views.bookinglistadder,name="bookinglistadder"),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('search-suggestions-professionals/', views.search_suggestions_prof, name='search_suggestions_prof'),
    path('checkout/',views.checkout_verification,name="checkout"),
    path('professionals/',views.booking_professional_page,name="professional"),
    path('professional/<int:professional_id>',views.professional_page,name='professionalspage'),
    path('professionalsform/<int:professional_id>',views.professionalsbookingform,name="professionalsbookingform"),
    path('succesfullyaddedprofessional/<int:professional_id>',views.professionalsbookinglistadder,name="professionalsbookinglistadder"),
    path('arview/<int:venue_id>',views.arview,name="arview")



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MainPage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

#below are the URL to call the function in view file
#in the mainpage app URL goes like
#        .../    just a slash.

app_name = 'MainPage'

urlpatterns = [
    path("",views.landing_view,name="mainpage"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Accounts/models.py
from django.db import models

# Create your models here.

Accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User 
from django.contrib import messages
from django.core.mail import send_mail,EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes,force_str
from . tokens import generate_token
from Ayojan import settings
from django.contrib.auth.decorators import login_required


#below funciton loads up profile_view html
def profile_view(request):
    user = request.user
    if not user.is_authenticated:  
        return redirect('Accounts/login_page.html')
    return render(request, 'Accounts/personal_info.html')


#below funciton loads up login_page html
def login_view(request):
    if request.method == 'POST':
        #below the variable username and password store the values provided in login_page.html
        #under the input tage with name = 'USERNAME' and 'PASSWORD'
        username_or_email = request.POST['USERNAME_OR_EMAIL']
        password = request.POST['PASSWORD']

        user = authenticate(request, username = username_or_email, password = password)

        #check if the authenticate returns an object (if user exist) or None (if it doesn't)
        if user is not None:
            login(request, user)
            return redirect('MainPage:mainpage')
        else:
            messages.error(request, 'Invalid Username or Password')
            return redirect('Accounts:login_view')
    else:
        return render(request, 'Accounts/login_page.html')


#below funciton loads up signup_page html
def signup_view(request):
    #below i have taken the response provided by the user on the form and stored it an variable
    if request.method == "POST":
        username = request.POST['USERNAME']
        first_name = request.POST['FIRST_NAME']
        last_name = request.POST['LAST_NAME']
        email = request.POST['EMAIL']
        password = request.POST['PASSWORD']
        confirm_password = request.POST['CONFIRM_PASSWORD']

        #checking it password is equal confirm password
        if password != confirm_password:
            messages.error(request, "Password don't match")
            return redirect('Accounts:signup_view')

        # Checking if username or email already exists
        if User.objects.filter(username=username).exists():
            messages.error(request,"Username already exsist")
            return redirect('Accounts:signup_view')


        if User.objects.filter(email=email).exists():
            messages.error(request,"Email already exsist")
            return redirect('Accounts:signup_view')


        myuser = User.objects.create_user(username,email,password)
        myuser.first_name = first_name
        myuser.last_name = last_name
        myuser.is_active = False
    
        myuser.save() 

        
        #Welcome Email
        subject = "Welcome to Ayojan"
        message = f"Hello, {first_name}!!\nYour Ayojan journey will be as smooth as possible.\nThank you for visiting our website.\nWe have sent you a confirmation email. Please check it.\n"
        from_email = settings.EMAIL_HOST_USER
        to_list = [myuser.email]
        send_mail(subject,message,from_email,to_list,fail_silently=True)
        

        #Confirmation Email

        current_site = get_current_site(request)
        email_subject = "Email Confirmation For Ayojan Website"
        message_2 = render_to_string('email_confirmation.html',{
            'name' : myuser.first_name,
            'domain' : current_site.domain,
            'uid' : urlsafe_base64_encode(force_bytes(myuser.pk)),
            'token' : generate_token.make_token(myuser),
        })


        email = EmailMessage(
            email_subject,
            message_2,
            settings.EMAIL_HOST_USER,
            [myuser.email],
        )
        email.fail_silently = True
        email.send()

        return render(request, 'Accounts/login_page.html')  
    else:
        return render(request, 'Accounts/signup_page.html')


def activate_acc(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)
    except(TypeError,ValueError,OverflowError,User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        myuser.backend = 'django.contrib.auth.backends.ModelBackend' 
        myuser.is_active=True
        myuser.save()
        login(request,myuser,backend='django.contrib.auth.backends.ModelBackend')
        return redirect('MainPage:mainpage')
    else:
        return render(request,'activation_failed.html')



def signout(request):
    logout(request)
    return redirect('MainPage:mainpage')


def profile_info(request):
    user = request.user
    if not user.is_authenticated:  
        return redirect('Accounts/login_page.html')
    return render(request, 'Accounts/personal_info.html')

def check_auth(request):
    field_to_change = request.GET.get('field')
    if request.method == "POST":
        myuser = request.user
        if authenticate(request, username=myuser.email, password=request.POST['password']):
            if field_to_change == "changeinfo":
                return render(request, 'Accounts/change_name.html')
            else :
                return render(request,'Accounts/change_password.html')
        else:
            return redirect('Accounts:profile_view')
    else:
        return render(request, 'Accounts/confirm_password.html')

def change_name(request):
    myuser = request.user
    
    if request.method == "POST":
        if "changeusernameto" in request.POST and request.POST["changeusernameto"]:
            myuser.username = request.POST["changeusernameto"]
        if "changefirstnameto" in request.POST and request.POST["changefirstnameto"]:
            myuser.first_name = request.POST["changefirstnameto"]
        if "changelastnameto" in request.POST and request.POST["changelastnameto"]:
            myuser.last_name = request.POST["changelastnameto"]
        if "changeemailto" in request.POST and request.POST["changeemailto"]:
            myuser.email = request.POST["changeemailto"]
        myuser.save()
        return redirect('Accounts:profile_view')
    else:
        return render(request, 'Accounts/change_name.html')
    
from django.contrib.auth import update_session_auth_hash  # To prevent logging out after password change

def change_pass(request):
    myuser = request.user

    if request.method == "POST":
        password = request.POST.get('Password')
        confirm_password = request.POST.get('CONFIRM_PASSWORD')

        # Check if both password fields match
        if password and confirm_password and password == confirm_password:
            myuser.set_password(password)  # Set the new password
            myuser.save()

            # Update the session with the new password, so the user doesn't get logged out
            update_session_auth_hash(request, myuser)

            return redirect('Accounts:profile_view')
        else:
            # If passwords don't match, render the form again with an error message
            return render(request, 'Accounts/change_password.html', {
                'error': 'Passwords do not match'
            })
    else:
        return render(request, 'Accounts/change_password.html')

Accounts/templates/Accounts/change_name.html
<!DOCTYPE html>
<html>
    {% load static %}
    {% load socialaccount %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="..{% static 'Accounts/CSS/profile_CS.css'%}" />
    </head>
    <body>
        <div class="navbar">
            <a href="{% url 'MainPage:mainpage'%}"><img id="navbar-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo"></a>
        </div>
        <div>
            <span>Username :</span>
            <form action="{% url 'Accounts:change' %}" method="POST">
                {% csrf_token %}
                    <div id="username">
                        Current : {{user.username}}
                        <div id = "username">
                                <input name="changeusernameto" type="text">
                        </div>
                    </div>
            
                </div>
                <div id="name">
                    <div>
                        <span>First Name :</span>
                        <div id="username">
                            Current : {{user.first_name}}
                            <div id = "username">
                                    <input name="changefirstnameto" type="text">
                   
                            </div>
                        </div>
                    </div>
                    <div>
                        <span>Last Name :</span>
                        <div id="username">
                            Current : {{user.last_name}}
                            <div id = "username">
                                    <input name="changelastnameto" type="text">
                            </div>
                        </div>
                    </div>
                    <div>
                        <span>Email :</span>
                        <div id="username">
                            Current : {{user.email}}
                            <div id = "username">
                                    <input name="changeemailto" type="text">
                            </div>
                        </div>
                    </div>
                </div>
                <button id="submit-button" type="submit">Change</button>
            </form>        
    </body>        
</html>

Accounts/templates/Accounts/change_password.html
<!DOCTYPE html>
<html>
    {% load static %}
    {% load socialaccount %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="..{% static 'Accounts/CSS/profile_CS.css'%}" />
    </head>
    <body>
        <div class="navbar">
            <a href="{% url 'MainPage:mainpage'%}"><img id="navbar-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo"></a>
        </div>
        <div>
            <span>Username :</span>
            <form action="{% url 'Accounts:change_pass' %}" method="POST">
                {% csrf_token %}
                    <div id="username">
                        Current : {{user.username}}
                    </div>
                </div>
                <div id="name">
                    <div>
                        <span>New Password</span>
                        <div id="username">
                            <div id = "username">
                                    <input name="Password" type="text">
                            </div>
                        </div>
                        <span>Comfirm Password</span>
                        <div id="username">
                            <div id = "username">
                                    <input name="CONFIRM_PASSWORD" type="text">
                            </div>
                        </div>
                    </div>

                <button id="submit-button" type="submit">Change</button>
            </form>        
    </body>        
</html>

Accounts/templates/Accounts/confirm_password.html
<!DOCTYPE html>
<html>
    {% load static %}
    {% load socialaccount %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="..{% static 'Accounts/CSS/profile_CS.css'%}" />
    </head>
    <body>
        <div class="navbar">
            <a href="{% url 'MainPage:mainpage'%}"><img id="navbar-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo"></a>
        </div>
        <div>
            <span>Username :</span>
            <form method="POST">
                {% csrf_token %}
                    <div id="username">
                        {{user.username}}
                        <div id = "username">
                                <input name="password" type="password">
                        </div>
                    </div>

                <button id="submit-button" type="submit">Submit</button>
            </form>        
    </body>        
</html>

Accounts/templates/Accounts/login_page.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  {% load socialaccount %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="..{% static 'Accounts/CSS/login_CS.css' %}" rel="stylesheet">

  <title>Login Page</title>
</head>

<body>
  {% if user.is_authenticated %}
  <script type="text/javascript">
      window.location.href = "{% url 'MainPage:mainpage' %}";
  </script>
  {% endif %}
  <div class="navbar">
    <a href="{% url 'MainPage:mainpage' %}"><img id="navbar-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo"></a>
  </div>
  <div class="middle">
    <div class="login-div">
      <img id="login-div-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo">
      <div class="login-form-div">
        <form action="{% provider_login_url 'google' %}" method="post">
          {% csrf_token %}
          <button type="submit" id="google-login-button"><img id="google-logo" src="..{% static 'Accounts/IMAGES/icons8-google-logo-48.png'%}"><span id="google-login-text">Login</span></button>
        </form>
        <span>-----Or-----</span>
        <form class="login-form" method="POST">
          {% csrf_token %}
          <input type="text" name="USERNAME_OR_EMAIL" id="USERNAME_OR_EMAIL" placeholder="USERNAME or Email">
          <input type="password" name="PASSWORD" id="PASSWORD" placeholder="PASSWORD">
          <button id="submit-button" type="submit">Login</button>
        </form>
        <div class="signup-div">
          <span>Don't Have an account</span>
          <a href="{% url 'Accounts:signup_view'%}"><button id="google-login-button">Sign Up</button></a>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

Accounts/templates/Accounts/personal_info.html
{% extends 'Accounts/profile_view.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="..{% static 'Accounts/CSS/profile_CS.css'%}">
   
<div class="personal-details">
    <div>
        <span>Username :</span>
        <div id="username">
            {{user.username}}
            <a href="{% url 'Accounts:change_name' %}?field=changeinfo"><img id="pencil" src=".{% static 'Accounts/IMAGES/pencil.jpg'%}" alt="edit"></a>
        </div>

    </div>
    <div id="name">
        <div>
            <span>First Name :</span>
            <div id="username">
                {{user.first_name}}
                <a href="{% url 'Accounts:change_name' %}?field=changeinfo"><img id="pencil" src=".{% static 'Accounts/IMAGES/pencil.jpg'%}" alt="edit"></a>
            </div>
        </div>
        <div>
            <span>Last Name :</span>
            <div id="username">
                {{user.last_name}}
                <a href="{% url 'Accounts:change_name' %}?field=changeinfo"><img id="pencil" src=".{% static 'Accounts/IMAGES/pencil.jpg'%}" alt="edit"></a>
            </div>
        </div>
    </div>
    <div>
        <span>Email :</span>
        <div id="username">
            {{user.email}}
            <a href="{% url 'Accounts:change_name' %}?field=changeinfo"><img id="pencil" src=".{% static 'Accounts/IMAGES/pencil.jpg'%}" alt="edit"></a>
        </div>
    </div>
    <div id="username">
        <a href="{% url 'Accounts:change_name' %}?field=changepass"><span>Change Password</span></a>
    </div>
</div>

{% endblock content %}

Accounts/templates/Accounts/profile_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=".{% static 'Accounts/CSS/profile_CS.css'%}">
    <title>Account Profile</title>
</head>
<body>

    <div class="navbar">
        <label for="sidebar-active" class="open-sidebar-button">
            <svg xmlns="http://www.w3.org/2000/svg" height="32" viewBox="0 -960 960 960" width="32"><path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/></svg>
        </label>
        <div class="left-navbar">
            <a href="{% url 'MainPage:mainpage' %}"><img id="navbar-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo"></a>
            
            <div class="nav-btn">
                <a href="{% url 'Booking:bookingpage'%}">Venues</a>
            </div>
            <div class="nav-btn">
                <a href="{% url 'Booking:professional'%}">Professionals</a>
            </div>
        
       </div>
 
            
       <div class="right-navbar">
            <div class="profile-or-login">
                {% if user.is_authenticated %}
                    <a href="{% url 'Accounts:profile_view' %}"><svg class="profile-btn-icon" xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="#000000"><path d="M226-262q59-42.33 121.33-65.5 62.34-23.17 132.67-23.17 70.33 0 133 23.17T734.67-262q41-49.67 59.83-103.67T813.33-480q0-141-96.16-237.17Q621-813.33 480-813.33t-237.17 96.16Q146.67-621 146.67-480q0 60.33 19.16 114.33Q185-311.67 226-262Zm253.88-184.67q-58.21 0-98.05-39.95Q342-526.58 342-584.79t39.96-98.04q39.95-39.84 98.16-39.84 58.21 0 98.05 39.96Q618-642.75 618-584.54t-39.96 98.04q-39.95 39.83-98.16 39.83ZM480.31-80q-82.64 0-155.64-31.5-73-31.5-127.34-85.83Q143-251.67 111.5-324.51T80-480.18q0-82.82 31.5-155.49 31.5-72.66 85.83-127Q251.67-817 324.51-848.5T480.18-880q82.82 0 155.49 31.5 72.66 31.5 127 85.83Q817-708.33 848.5-635.65 880-562.96 880-480.31q0 82.64-31.5 155.64-31.5 73-85.83 127.34Q708.33-143 635.65-111.5 562.96-80 480.31-80Zm-.31-66.67q54.33 0 105-15.83t97.67-52.17q-47-33.66-98-51.5Q533.67-284 480-284t-104.67 17.83q-51 17.84-98 51.5 47 36.34 97.67 52.17 50.67 15.83 105 15.83Zm0-366.66q31.33 0 51.33-20t20-51.34q0-31.33-20-51.33T480-656q-31.33 0-51.33 20t-20 51.33q0 31.34 20 51.34 20 20 51.33 20Zm0-71.34Zm0 369.34Z"/></svg></a>
                {% else %}
                    <a href="{% url 'Accounts:login_view' %}"><svg class="login-btn-icon" xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 -960 960 960" width="30px" fill="#000000"><path d="M480.67-120v-66.67h292.66v-586.66H480.67V-840h292.66q27 0 46.84 19.83Q840-800.33 840-773.33v586.66q0 27-19.83 46.84Q800.33-120 773.33-120H480.67Zm-63.34-176.67-47-48 102-102H120v-66.66h351l-102-102 47-48 184 184-182.67 182.66Z"/></svg></a>
                {% endif %}
            </div>
            <div class="cart-button">
                <a href="{% url 'Booking:cartpage' %}"><svg class="cart-btn-icon" xmlns="http://www.w3.org/2000/svg" height="34px" viewBox="0 -960 960 960" width="34px" fill="#000000"><path d="M284.53-80.67q-30.86 0-52.7-21.97Q210-124.62 210-155.47q0-30.86 21.98-52.7Q253.95-230 284.81-230t52.69 21.98q21.83 21.97 21.83 52.83t-21.97 52.69q-21.98 21.83-52.83 21.83Zm400 0q-30.86 0-52.7-21.97Q610-124.62 610-155.47q0-30.86 21.98-52.7Q653.95-230 684.81-230t52.69 21.98q21.83 21.97 21.83 52.83t-21.97 52.69q-21.98 21.83-52.83 21.83ZM238.67-734 344-515.33h285.33l120-218.67H238.67ZM206-800.67h589.38q22.98 0 34.97 20.84 11.98 20.83.32 41.83L693.33-490.67q-11 19.34-28.87 30.67-17.87 11.33-39.13 11.33H324l-52 96h487.33V-286H278q-43 0-63-31.83-20-31.84-.33-68.17l60.66-111.33-149.33-316H47.33V-880h121.34L206-800.67Zm138 285.34h285.33H344Z"/></svg></a>
            </div>
    </div>
    </div>
    <div class="middle">
        <div class="left-side-panel">
           <div class="img-div"><img id="profile-img" src=".{% static 'Accounts/IMAGES/pfp.png'%}" alt="logo"></div>
            <div class="options">
                <div><a href="{% url 'Accounts:profile_view'%}"><button id="option">Personal Info</button></a></div>
                <div><a href="#"><button id="option">Booking History</button></a></div>
                <div><a href="#"><button id="option">Reviews Left</button></a></div>
                <div><a href="#"><button id="option">About us</button></a></div>
                <div><a href="{% url 'Accounts:signout'%}"><button id="option">Log Out</button></a></div>
            </div>

        </div>
        <div class="left-side-panel-mobile">
            <input type="checkbox" id="sidebar-active">
            <label id="overlay" for="sidebar-active"></label>
            <div class="links-container">
              <label for="sidebar-active" class="close-sidebar-button">
                <svg xmlns="http://www.w3.org/2000/svg" height="32" viewBox="0 -960 960 960" width="32"><path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/></svg>
              </label>
        
              <div><a href="{% url 'Accounts:personal_info'%}"><button id="option">Personal Info</button></a></div>
              <div><a href="#"><button id="option">Transaction History</button></a></div>
              <div><a href="#"><button id="option">Booking History</button></a></div>
              <div><a href="#"><button id="option">Reviews Left</button></a></div>
              <div><a href="#"><button id="option">About us</button></a></div>
              <div><a href="#"><button id="option">Log Out</button></a></div>
              
            </div>
        </div>
        
        <div class="right-side-panel">

            {% block content %}

            {% endblock content %}
        </div>
    </div>

</body>
</html>

Accounts/templates/Accounts/signup_page.html
<!DOCTYPE html>
<html>
    {% load static %}
    {% load socialaccount %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="..{% static 'Accounts/CSS/signup_CS.css'%}" />
    </head>
    <body>
        <div class="navbar">
          <a href="{% url 'MainPage:mainpage' %}"><img id="navbar-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo"></a>
        </div>
        <div class="middle">
            <div class="signup-div">
                <img id="signup-div-logo" src="..{% static 'Accounts/IMAGES/ayojan-logo1.png'%}" alt="logo">
                <div class="signup-form-div">
                    {% if messages %}
                        <div>
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                  <form action="{% provider_login_url 'google' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" id="google-login-button"><img id="google-logo" src="..{% static 'Accounts/IMAGES/icons8-google-logo-48.png'%}"><span id="google-login-text">Login</span></button>
                  </form>
                  <span>-----Or-----</span>
                  <form class="signup-form" method="POST">
                    {% csrf_token %}
                    <input type="text" name="USERNAME" id="USERNAME" placeholder="USERNAME">
                    <input type="EMAIL" name="EMAIL" id="EMAIL" placeholder="EMAIL">
                    <input type="text" name="FIRST_NAME" id="FIRST-NAME" placeholder="FIRST NAME">
                    <input type="text" name="LAST_NAME" id="LAST-NAME" placeholder="LAST NAME">
                    <input type="password" name="PASSWORD" id="PASSWORD" placeholder="PASSWORD">
                    <input type="password" name="CONFIRM_PASSWORD" id="PASSWORD" placeholder="CONFIRM PASSWORD">
                    <button id="submit-button" type="submit">Signup</button>
                  </form>
                  <div class="login-div">
                    <span>Already Have an account</span>
                    <a href="{% url 'Accounts:login_view'%}"><button id="google-login-button">Login</button></a>
                  </div>
                </div>
              </div>
        </div>
    </body>        
</html>